import {useEffect,useRef,useState} from 'react';
import {SECTIONS,pickDistinctQuestions} from './SafetyModule.jsx';
const bg='#0A0F1E',panel='#111827',teal='#14B8A6',light='#F9FAFB',muted='#AAB5C5';
const input={width:'100%',boxSizing:'border-box',padding:13,borderRadius:9,background:'#0A0F1E',border:'1px solid #334155',color:light,fontSize:16};
const button={background:teal,border:0,borderRadius:9,color:'#052722',fontWeight:800,padding:'13px 17px',cursor:'pointer',fontSize:15};
const randomize=(xs)=>[...xs].sort(()=>Math.random()-.5);
const selectQuestions=i=>pickDistinctQuestions(i,2).map(q=>({prompt:q[0],options:randomize(q[1].map((label,n)=>({label,correct:n===q[2]}))),answered:false,attempts:0}));
const sid=()=>`southwest-worker-preview-session`;
const LANGUAGES=[['en','English'],['fr','Français'],['es','Español'],['ar','العربية'],['uk','Українська'],['de','Deutsch']];
const UI_STRINGS={
 en:['Choose your language','Register once; upload a photo or complete orientation in either order.','Complete Site Orientation','Upload Safety Certificates','Take photo or choose PDF','Submit for Southwest review','Listen','Read and understand','Knowledge check','Continue','Back','Correct!','Not quite — try again','The translation is a draft. Ask Southwest for help if anything is unclear.'],
 fr:['Choisissez votre langue','Inscrivez-vous une seule fois. Vous pouvez téléverser un certificat ou suivre la formation dans l’ordre souhaité.','Suivre la formation de sécurité','Téléverser des certificats','Prendre une photo ou choisir un PDF','Envoyer pour vérification','Écouter','J’ai lu et compris','Vérification des connaissances','Continuer','Retour','Bonne réponse !','Pas tout à fait — réessayez','Traduction provisoire. Demandez de l’aide à Southwest si quelque chose est flou.'],
 es:['Elija su idioma','Regístrese una sola vez. Puede subir certificados o completar la orientación en cualquier orden.','Completar orientación de seguridad','Subir certificados','Tomar foto o elegir PDF','Enviar para revisión','Escuchar','He leído y comprendido','Preguntas de repaso','Continuar','Volver','¡Correcto!','Inténtelo de nuevo','Traducción provisional. Pida ayuda a Southwest si algo no está claro.'],
 ar:['اختر لغتك','سجّل مرة واحدة. يمكنك تحميل الشهادات أو إكمال التوجيه بأي ترتيب.','إكمال توجيه السلامة','تحميل شهادات السلامة','التقط صورة أو اختر ملف PDF','إرسال للمراجعة','استمع','قرأت وفهمت','أسئلة المراجعة','متابعة','عودة','إجابة صحيحة','حاول مرة أخرى','الترجمة مسودة. اطلب المساعدة من ساوث ويست إذا لم تفهم شيئًا.'],
 uk:['Оберіть мову','Зареєструйтеся один раз. Можна завантажити сертифікати або пройти інструктаж у будь-якому порядку.','Пройти інструктаж з безпеки','Завантажити сертифікати','Зробити фото або вибрати PDF','Надіслати на перевірку','Прослухати','Я прочитав(ла) та зрозумів(ла)','Перевірка знань','Далі','Назад','Правильно!','Спробуйте ще раз','Це попередній переклад. Якщо щось незрозуміло, зверніться до Southwest.'],
 de:['Sprache auswählen','Einmal registrieren. Zertifikate hochladen oder Sicherheitseinweisung abschließen – in beliebiger Reihenfolge.','Sicherheitseinweisung durchführen','Zertifikate hochladen','Foto machen oder PDF auswählen','Zur Prüfung einreichen','Vorlesen','Ich habe diesen Abschnitt gelesen und verstanden','Wissensfragen','Weiter','Zurück','Richtig!','Bitte erneut versuchen','Übersetzung ist vorläufig. Bitte fragen Sie Southwest, wenn etwas unklar ist.']
};

async function api(action,fields){const r=await fetch('/api/worker-portal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...fields})});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
function Labeled({label,children}){return <label style={{display:'grid',gap:6,fontSize:13,color:muted}}>{label}{children}</label>}
export default function WorkerPortal(){
 const [language,setLanguage]=useState(()=>sessionStorage.getItem('safety-lang')||'en'),[localized,setLocalized]=useState({}),[translating,setTranslating]=useState(false),[token,setToken]=useState(()=>new URLSearchParams(window.location.search).get('session')||sessionStorage.getItem(sid())||''),[worker,setWorker]=useState(null),[form,setForm]=useState({name:'',company:'',trade:'',occupation:''}),[consent,setConsent]=useState(false),[screen,setScreen]=useState('home'),[error,setError]=useState(''),[working,setWorking]=useState(false),[cert,setCert]=useState({type:'',issued_date:'',expiry_date:'',notes:''}),[file,setFile]=useState(null),[step,setStep]=useState(0),[questions,setQuestions]=useState(()=>selectQuestions(0)),[ack,setAck]=useState(false),[sections,setSections]=useState([]),[signature,setSignature]=useState(''),[declaration,setDeclaration]=useState(false);
 useEffect(()=>{sessionStorage.setItem('safety-lang',language);window.speechSynthesis?.cancel?.()},[language]);
 const T=(i)=>UI_STRINGS[language]?.[i]||UI_STRINGS.en[i];
 const spoken=(text)=>{if(!('speechSynthesis' in window))return setError('Audio is not available on this device');window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=({en:'en-CA',fr:'fr-CA',es:'es-ES',ar:'ar',uk:'uk-UA',de:'de-DE'})[language];u.rate=.9;window.speechSynthesis.speak(u)};
 const entered=useRef(Date.now()),visible=useRef(0),hidden=useRef(false),started=useRef(new Date().toISOString());
 const act=async(action,data={},callback)=>{setWorking(true);setError('');try{const res=await api(action,data);callback?.(res);return res;}catch(e){setError(e.message);return null;}finally{setWorking(false)}};
 useEffect(()=>{if(token){sessionStorage.setItem(sid(),token);act('profile',{token},r=>setWorker(r.worker));}},[]);
 useEffect(()=>{const fn=()=>{if(document.hidden&&!hidden.current){visible.current+=Date.now()-entered.current;hidden.current=true}else if(!document.hidden&&hidden.current){entered.current=Date.now();hidden.current=false}};document.addEventListener('visibilitychange',fn);return()=>document.removeEventListener('visibilitychange',fn)},[]);
 const time=()=>Math.round((visible.current+(!hidden.current?Date.now()-entered.current:0))/1000);
 function logout(){sessionStorage.removeItem(sid());setToken('');setWorker(null);setScreen('home')}
 async function register(){const r=await act('register',{...form,consent,language},r=>{sessionStorage.setItem(sid(),r.token);setToken(r.token);setWorker(r.worker)});if(r)setScreen('home')}
 async function addCert(){if(!file)return setError('Choose a photo or PDF');if(file.size>2100000)return setError('Choose a file smaller than 2 MB');setWorking(true);setError('');try{const data=await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(file)});const r=await api('ticket_auto',{token,attachment:{name:file.name,type:file.type,data}});setWorker(r.worker);setCert({type:'',issued_date:'',expiry_date:'',notes:''});setFile(null);setScreen('home')}catch(e){setError(e.message)}finally{setWorking(false)}}
 function proceed(){if(!ack||questions.some(q=>!q.answered))return;const section={title:SECTIONS[step].title,language,displayed_translation:language!=='en'?{title:loc?.title||null,points:loc?.points||null,questions:loc?.questions||null}:null,elapsed_seconds:time(),acknowledged_at:new Date().toISOString(),questions:questions.map(q=>({prompt:q.prompt,attempts:q.attempts,correct:true}))};setSections(s=>[...s,section]);visible.current=0;entered.current=Date.now();hidden.current=document.hidden;setAck(false);if(step===SECTIONS.length-1)setScreen('sign');else{setStep(step+1);setQuestions(selectQuestions(step+1))}}
 async function complete(){const r=await act('orientation',{token,sections,language,signature,acknowledged:declaration,started_at:started.current},r=>setWorker(r.worker));if(r){setScreen('home');setSections([]);setStep(0);setQuestions(selectQuestions(0));setSignature('');setDeclaration(false)}}
 const start=()=>{setStep(0);setSections([]);setQuestions(selectQuestions(0));setAck(false);started.current=new Date().toISOString();visible.current=0;entered.current=Date.now();hidden.current=document.hidden;setScreen('lesson')};
 useEffect(()=>{if(!worker||screen!=='lesson'||language==='en')return;let cancelled=false;const q=questions.map(v=>({prompt:v.prompt,options:v.options.map(o=>o.label)}));const key=language+'-'+step+'-'+q.map(v=>v.prompt).join('|');if(localized[key])return;setTranslating(true);api('translate',{token,language,section_index:step,title:SECTIONS[step].title,points:SECTIONS[step].points,questions:q}).then(r=>{if(!cancelled)setLocalized(x=>({...x,[key]:r.translation}))}).catch(()=>{if(!cancelled)setError('Translation unavailable. English text shown; ask Southwest for language help.')}).finally(()=>{if(!cancelled)setTranslating(false)});return()=>{cancelled=true}},[worker,screen,step,language,questions.map(q=>q.prompt).join('|')]);
 const translationKey=language+'-'+step+'-'+questions.map(q=>q.prompt).join('|');const loc=localized[translationKey];
 const item=(children)=> <div style={{background:panel,border:'1px solid #263448',padding:18,borderRadius:14,marginBottom:15}}>{children}</div>;
 return <main style={{minHeight:'100vh',background:bg,color:light,fontFamily:'Segoe UI,Arial,sans-serif',padding:'22px 14px 60px'}}><div style={{maxWidth:560,margin:'auto'}}><header style={{marginBottom:22}}><div style={{color:teal,fontWeight:800,letterSpacing:1,fontSize:13}}>SOUTHWEST · FORTUNA</div><label style={{display:'grid',gap:6,marginTop:15,color:muted,fontSize:13}}>{T(0)}<select aria-label='Orientation language' style={input} value={language} onChange={e=>setLanguage(e.target.value)}>{LANGUAGES.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><h1 style={{fontSize:25,margin:'9px 0'}}>Worker Safety & Orientation</h1><div style={{color:muted,fontSize:13}}>v21.2 test portal · No staff dashboard access</div></header>{error&&<div role="alert" style={{padding:12,background:'#541d27',borderRadius:9,color:'#fecaca',marginBottom:16}}>{error}</div>}
 {!worker?item(<><h2>Worker registration</h2><p style={{color:muted}}>{T(1)}</p><div style={{display:'grid',gap:14}}>{[['Full name','name'],['Company','company'],['Trade','trade'],['Occupation','occupation']].map(([label,k])=><Labeled key={k} label={label}><input style={input} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></Labeled>)}<label style={{display:'flex',gap:9,fontSize:13}}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I understand these details will be reviewed by Southwest safety staff.</label><button style={button} disabled={working||!consent||!form.name||!form.company||!form.trade} onClick={register}>Create my worker profile</button><p style={{color:muted,fontSize:12}}>Already registered? Ask Southwest staff for a secure returning-worker link. Registering again won't open an existing profile.</p></div></>):<>
 <div style={{display:'flex',justifyContent:'space-between',gap:9,alignItems:'center',marginBottom:12}}><div><strong>{worker.name}</strong><div style={{color:muted,fontSize:12}}>{worker.trade} · {worker.company}</div></div><button style={{...button,background:'#253348',color:light,padding:9}} onClick={logout}>Exit</button></div>
 {screen==='home'&&<>{item(<><h2 style={{marginTop:0}}>What would you like to do?</h2><p style={{color:muted}}>Either option can be completed first.</p><div style={{display:'grid',gap:12}}><button style={button} onClick={start}>{T(2)} →</button><button style={{...button,background:'#27394b',color:light}} onClick={()=>setScreen('upload')}>{T(3)} →</button></div></>)}{item(<><h3>Your current status</h3><p>Orientation: <strong>{worker.orientation?.approval_status==='approved'?'Verified by Southwest':worker.orientation?.status==='completed'?'Submitted · awaiting safety manager':'Not completed'}</strong></p><p>Certificates submitted: <b>{worker.tickets?.length||0}</b></p>{(worker.tickets||[]).map(t=><p key={t.id} style={{color:muted,fontSize:13}}>{t.type} · {t.expiry_date||'No expiry entered'} · {t.status}</p>)}<p style={{color:muted,fontSize:12}}>Uploaded certificates are not verified until Southwest reviews them.</p></>)}</>}
 {screen==='upload'&&item(<><h2>{T(3)}</h2><p style={{color:muted}}>Take a clear photograph or upload a PDF. Southwest will extract and verify the details. No typing needed.</p><div style={{display:'grid',gap:14}}><Labeled label={T(4)}><input style={input} type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></Labeled>{file&&<p style={{color:teal,fontSize:13}}>{file.name}</p>}<button style={button} disabled={working||!file} onClick={addCert}>{working?'Reading and submitting…':T(5)}</button><button style={{...button,background:'#253348',color:light}} onClick={()=>setScreen('home')}>{T(10)}</button></div></>)}
 {screen==='lesson'&&item(<><div style={{color:teal,fontWeight:800}}>SECTION {step+1} OF {SECTIONS.length}</div><h2>{loc?.title||SECTIONS[step].title}</h2><button style={{...button,background:'#263548',color:light}} onClick={()=>spoken([loc?.title||SECTIONS[step].title,...(loc?.points||SECTIONS[step].points)].join('. '))}>{T(6)} ▶</button>{(loc?.points||SECTIONS[step].points).map((p,i)=><p key={i} style={{background:bg,padding:12,borderRadius:8,lineHeight:1.6}}>{p}</p>)}<label style={{display:'flex',gap:10,margin:'16px 0'}}><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> {T(7)}</label><h3>{T(8)}</h3>{questions.map((q,i)=><div key={q.prompt} style={{borderTop:'1px solid #334155',padding:'14px 0'}}><strong>{i+1}. {loc?.questions?.[i]?.prompt||q.prompt}</strong><button style={{...button,marginLeft:8,padding:5,background:'#263548',color:light}} onClick={()=>spoken(loc?.questions?.[i]?.prompt||q.prompt)}>▶ {T(6)}</button>{q.options.map((choice,j)=><button key={j} disabled={q.answered} onClick={()=>setQuestions(arr=>arr.map((x,n)=>n===i?{...x,attempts:x.attempts+1,answered:choice.correct}:x))} style={{...button,width:'100%',textAlign:'left',marginTop:9,background:q.answered&&choice.correct?'#18392f':'#263548',color:light}}>{loc?.questions?.[i]?.options?.[j]||choice.label}</button>)}<p style={{fontSize:13,color:q.answered?'#22C55E':muted}}>{q.answered?T(11):q.attempts?T(12):T(8)}</p></div>)}{language!=='en'&&<p style={{color:'#EAB308',fontSize:12}}>{T(13)}</p>}<button style={{...button,width:'100%'}} disabled={translating||!ack||questions.some(q=>!q.answered)} onClick={proceed}>{T(9)} →</button></>)}
 {screen==='sign'&&item(<><h2>Declaration and signature</h2><p style={{lineHeight:1.7}}>I certify that I have completed the Southwest site orientation, understand my responsibilities and will follow site safety practices and applicable Nova Scotia requirements.</p><label style={{display:'flex',gap:9,marginBottom:15}}><input type="checkbox" checked={declaration} onChange={e=>setDeclaration(e.target.checked)}/> I agree to this declaration.</label><Labeled label="Type your full name as your signature"><input style={input} value={signature} onChange={e=>setSignature(e.target.value)}/></Labeled><p style={{color:muted,fontSize:13}}>Completion is pending safety manager verification.</p><button style={{...button,width:'100%'}} disabled={working||!declaration||!signature.trim()} onClick={complete}>Submit orientation for review</button></>)}
 </>}</div></main>;
}
