import {useEffect,useRef,useState} from 'react';
import {SECTIONS,pickDistinctQuestions} from './SafetyModule.jsx';
const bg='#0A0F1E',panel='#111827',teal='#14B8A6',light='#F9FAFB',muted='#AAB5C5';
const input={width:'100%',boxSizing:'border-box',padding:13,borderRadius:9,background:'#0A0F1E',border:'1px solid #334155',color:light,fontSize:16};
const button={background:teal,border:0,borderRadius:9,color:'#052722',fontWeight:800,padding:'13px 17px',cursor:'pointer',fontSize:15};
const randomize=(xs)=>[...xs].sort(()=>Math.random()-.5);
const selectQuestions=i=>pickDistinctQuestions(i,2).map(q=>({prompt:q[0],options:randomize(q[1].map((label,n)=>({label,correct:n===q[2]}))),answered:false,attempts:0}));
const sid=()=>`southwest-worker-preview-session`;
const LANGUAGES=[['en','English'],['fr','Français'],['es','Español'],['ar','العربية'],['uk','Українська'],['de','Deutsch']];
const I18N={
 "en": [
  "Choose your language",
  "Register once; upload a photo or complete orientation in either order.",
  "Complete Site Orientation",
  "Upload Safety Certificates",
  "Take photo or choose PDF",
  "Submit for Southwest review",
  "Listen",
  "I have read and understood this section",
  "Knowledge check",
  "Continue",
  "Back",
  "Correct!",
  "Not quite — try again",
  "Draft translation. Ask Southwest for help if anything is unclear.",
  "Worker Safety & Orientation",
  "v21.4 test portal · No staff dashboard access",
  "Worker registration",
  "Full name",
  "Company",
  "Trade",
  "Occupation",
  "I understand these details will be reviewed by Southwest safety staff.",
  "Create my worker profile",
  "Already registered? Ask Southwest staff for a secure returning-worker link. Registering again will not open an existing profile.",
  "Exit",
  "What would you like to do?",
  "Either option can be completed first.",
  "Your current status",
  "Orientation",
  "Certificates submitted",
  "Verified by Southwest",
  "Submitted · awaiting safety manager",
  "Not completed",
  "No expiry listed",
  "Pending Southwest verification",
  "Verified",
  "Pending review",
  "Take a clear photo or upload a PDF. Southwest will extract and check the details. No typing needed.",
  "Reading and submitting…",
  "Section",
  "of",
  "Declaration and signature",
  "I confirm that I completed the Southwest site orientation, understand my responsibilities, and will follow site safety practices and applicable Nova Scotia requirements.",
  "I agree to this declaration.",
  "Type your full name as your signature",
  "Completion is pending safety manager verification.",
  "Submit orientation for review",
  "Translation unavailable. Do not continue in a language you do not understand. Ask Southwest for assistance.",
  "Audio is not available on this device",
  "Choose a photo or PDF",
  "Choose a file smaller than 2 MB",
  "Certificate submitted for Southwest review.",
  "Translating the safety information…",
  "Ask Southwest for help before continuing if anything is unclear."
 ],
 "fr": [
  "Choisissez votre langue",
  "Inscrivez-vous une seule fois; envoyez une photo ou suivez la formation dans l’ordre souhaité.",
  "Suivre la formation de sécurité",
  "Téléverser des certificats",
  "Prendre une photo ou choisir un PDF",
  "Envoyer pour vérification par Southwest",
  "Écouter",
  "J’ai lu et compris cette section",
  "Vérification des connaissances",
  "Continuer",
  "Retour",
  "Bonne réponse !",
  "Pas tout à fait — réessayez",
  "Traduction provisoire. Demandez de l’aide à Southwest si quelque chose est flou.",
  "Sécurité et accueil des travailleurs",
  "Portail de test v21.4 · Aucun accès au tableau de bord",
  "Inscription des travailleurs",
  "Nom complet",
  "Entreprise",
  "Métier",
  "Poste",
  "Je comprends que l’équipe de sécurité de Southwest examinera ces renseignements.",
  "Créer mon profil de travailleur",
  "Déjà inscrit ? Demandez à Southwest un lien de retour sécurisé. Une nouvelle inscription ne permet pas de retrouver un profil existant.",
  "Quitter",
  "Que souhaitez-vous faire ?",
  "Vous pouvez commencer par l’une ou l’autre option.",
  "Votre statut actuel",
  "Formation",
  "Certificats envoyés",
  "Vérifié par Southwest",
  "Envoyé · en attente du responsable sécurité",
  "Non terminé",
  "Aucune date d’expiration",
  "En attente de vérification par Southwest",
  "Vérifié",
  "En attente de vérification",
  "Prenez une photo nette ou téléversez un PDF. Southwest extraira et vérifiera les renseignements. Aucune saisie nécessaire.",
  "Lecture et envoi en cours…",
  "Section",
  "sur",
  "Déclaration et signature",
  "Je confirme avoir suivi la formation de sécurité Southwest, compris mes responsabilités et accepté de respecter les règles du chantier et les exigences applicables de la Nouvelle-Écosse.",
  "J’accepte cette déclaration.",
  "Saisissez votre nom complet comme signature",
  "La validation finale nécessite l’approbation du responsable sécurité.",
  "Envoyer la formation pour vérification",
  "Traduction indisponible. Ne continuez pas dans une langue que vous ne comprenez pas. Demandez de l’aide à Southwest.",
  "Lecture audio indisponible sur cet appareil",
  "Choisissez une photo ou un PDF",
  "Choisissez un fichier de moins de 2 Mo",
  "Certificat envoyé pour vérification par Southwest.",
  "Traduction des consignes de sécurité en cours…",
  "Demandez de l’aide à Southwest si quelque chose n’est pas clair."
 ],
 "es": [
  "Elija su idioma",
  "Regístrese una sola vez; suba una foto o complete la orientación en cualquier orden.",
  "Completar orientación de seguridad",
  "Subir certificados de seguridad",
  "Tomar foto o elegir PDF",
  "Enviar para revisión de Southwest",
  "Escuchar",
  "He leído y comprendido esta sección",
  "Comprobación de conocimientos",
  "Continuar",
  "Atrás",
  "¡Correcto!",
  "No es correcto — inténtelo de nuevo",
  "Traducción provisional. Pida ayuda a Southwest si algo no está claro.",
  "Seguridad y orientación de trabajadores",
  "Portal de prueba v21.4 · Sin acceso al panel del personal",
  "Registro de trabajadores",
  "Nombre completo",
  "Empresa",
  "Oficio",
  "Ocupación",
  "Entiendo que el personal de seguridad de Southwest revisará esta información.",
  "Crear mi perfil de trabajador",
  "¿Ya está registrado? Solicite a Southwest un enlace seguro para volver. Registrarse de nuevo no abre su perfil existente.",
  "Salir",
  "¿Qué desea hacer?",
  "Puede completar cualquiera de las dos opciones primero.",
  "Su estado actual",
  "Orientación",
  "Certificados enviados",
  "Verificado por Southwest",
  "Enviado · pendiente del responsable de seguridad",
  "No completado",
  "Sin fecha de vencimiento",
  "Pendiente de verificación por Southwest",
  "Verificado",
  "Pendiente de revisión",
  "Tome una foto clara o suba un PDF. Southwest extraerá y revisará los datos. No necesita escribirlos.",
  "Leyendo y enviando…",
  "Sección",
  "de",
  "Declaración y firma",
  "Confirmo que completé la orientación de seguridad de Southwest, comprendo mis responsabilidades y cumpliré las prácticas de seguridad del sitio y los requisitos aplicables de Nueva Escocia.",
  "Acepto esta declaración.",
  "Escriba su nombre completo como firma",
  "La finalización está pendiente de la verificación del responsable de seguridad.",
  "Enviar orientación para revisión",
  "Traducción no disponible. No continúe en un idioma que no comprenda. Solicite ayuda a Southwest.",
  "El audio no está disponible en este dispositivo",
  "Elija una foto o un PDF",
  "Elija un archivo de menos de 2 MB",
  "Certificado enviado para revisión de Southwest.",
  "Traduciendo las instrucciones de seguridad…",
  "Solicite ayuda a Southwest si algo no está claro."
 ],
 "ar": [
  "اختر لغتك",
  "سجّل مرة واحدة؛ يمكنك رفع صورة أو إكمال توجيه السلامة بأي ترتيب.",
  "إكمال توجيه السلامة",
  "رفع شهادات السلامة",
  "التقط صورة أو اختر ملف PDF",
  "إرسال لمراجعة ساوث ويست",
  "استمع",
  "قرأت هذا القسم وفهمته",
  "اختبار المعرفة",
  "متابعة",
  "رجوع",
  "إجابة صحيحة!",
  "ليست صحيحة — حاول مرة أخرى",
  "الترجمة أولية. اطلب المساعدة من ساوث ويست إذا كان شيء غير واضح.",
  "سلامة العمال والتوجيه",
  "بوابة اختبار الإصدار 21.4 · لا يمكن الوصول إلى لوحة الموظفين",
  "تسجيل العامل",
  "الاسم الكامل",
  "الشركة",
  "المهنة الحرفية",
  "الوظيفة",
  "أفهم أن فريق السلامة لدى ساوث ويست سيراجع هذه المعلومات.",
  "إنشاء ملف العامل",
  "هل سجلت من قبل؟ اطلب رابط عودة آمنًا من ساوث ويست. لن يفتح التسجيل مرة أخرى ملفك السابق.",
  "خروج",
  "ماذا تريد أن تفعل؟",
  "يمكنك البدء بأي من الخيارين.",
  "حالتك الحالية",
  "التوجيه",
  "الشهادات المرسلة",
  "تم التحقق من ساوث ويست",
  "تم الإرسال · بانتظار مسؤول السلامة",
  "لم يكتمل",
  "لا يوجد تاريخ انتهاء",
  "بانتظار تحقق ساوث ويست",
  "تم التحقق",
  "بانتظار المراجعة",
  "التقط صورة واضحة أو ارفع ملف PDF. ستستخرج ساوث ويست البيانات وتراجعها. لا حاجة للكتابة.",
  "جارٍ قراءة الملف وإرساله…",
  "القسم",
  "من",
  "الإقرار والتوقيع",
  "أؤكد أنني أكملت توجيه السلامة في موقع ساوث ويست، وفهمت مسؤولياتي، وسأتبع قواعد السلامة ومتطلبات نوفا سكوشا المعمول بها.",
  "أوافق على هذا الإقرار.",
  "اكتب اسمك الكامل كتوقيع",
  "إكمال التوجيه ينتظر موافقة مسؤول السلامة.",
  "إرسال التوجيه للمراجعة",
  "الترجمة غير متاحة. لا تتابع بلغة لا تفهمها. اطلب المساعدة من ساوث ويست.",
  "الصوت غير متاح على هذا الجهاز",
  "اختر صورة أو ملف PDF",
  "اختر ملفًا أصغر من 2 ميغابايت",
  "تم إرسال الشهادة لمراجعة ساوث ويست.",
  "جارٍ ترجمة تعليمات السلامة…",
  "اطلب المساعدة من ساوث ويست إذا لم يكن أي شيء واضحًا."
 ],
 "uk": [
  "Оберіть мову",
  "Зареєструйтеся один раз; завантажте фото або пройдіть інструктаж у будь-якому порядку.",
  "Пройти інструктаж із безпеки",
  "Завантажити сертифікати",
  "Зробити фото або вибрати PDF",
  "Надіслати на перевірку Southwest",
  "Прослухати",
  "Я прочитав(-ла) і зрозумів(-ла) цей розділ",
  "Перевірка знань",
  "Далі",
  "Назад",
  "Правильно!",
  "Неправильно — спробуйте ще раз",
  "Переклад попередній. Якщо щось незрозуміло, зверніться до Southwest.",
  "Безпека та інструктаж працівників",
  "Тестовий портал v21.4 · Без доступу до панелі персоналу",
  "Реєстрація працівника",
  "Повне ім’я",
  "Компанія",
  "Будівельна спеціальність",
  "Посада",
  "Я розумію, що служба безпеки Southwest перевірить ці дані.",
  "Створити профіль працівника",
  "Уже зареєстровані? Попросіть у Southwest захищене посилання для повернення. Повторна реєстрація не відкриє ваш профіль.",
  "Вийти",
  "Що ви хочете зробити?",
  "Можна почати з будь-якої дії.",
  "Ваш поточний статус",
  "Інструктаж",
  "Надіслано сертифікатів",
  "Підтверджено Southwest",
  "Надіслано · очікує менеджера з безпеки",
  "Не завершено",
  "Термін дії не вказано",
  "Очікує перевірки Southwest",
  "Перевірено",
  "Очікує перевірки",
  "Зробіть чітке фото або завантажте PDF. Southwest розпізнає та перевірить дані. Вводити вручну нічого не потрібно.",
  "Розпізнавання та надсилання…",
  "Розділ",
  "з",
  "Декларація та підпис",
  "Я підтверджую проходження інструктажу Southwest, розуміння своїх обов’язків і зобов’язуюся дотримуватися правил безпеки та чинних вимог Нової Шотландії.",
  "Я погоджуюся з декларацією.",
  "Введіть повне ім’я як підпис",
  "Завершення очікує підтвердження менеджера з безпеки.",
  "Надіслати інструктаж на перевірку",
  "Переклад недоступний. Не продовжуйте мовою, яку не розумієте. Зверніться по допомогу до Southwest.",
  "Аудіо недоступне на цьому пристрої",
  "Виберіть фото або PDF",
  "Виберіть файл менше 2 МБ",
  "Сертифікат надіслано на перевірку Southwest.",
  "Переклад інструкцій з безпеки…",
  "Зверніться до Southwest, якщо щось незрозуміло."
 ],
 "de": [
  "Sprache auswählen",
  "Einmal registrieren; Foto hochladen oder Sicherheitseinweisung abschließen – in beliebiger Reihenfolge.",
  "Sicherheitseinweisung abschließen",
  "Sicherheitszertifikate hochladen",
  "Foto aufnehmen oder PDF auswählen",
  "Zur Prüfung an Southwest senden",
  "Vorlesen",
  "Ich habe diesen Abschnitt gelesen und verstanden",
  "Wissensprüfung",
  "Weiter",
  "Zurück",
  "Richtig!",
  "Nicht richtig – bitte erneut versuchen",
  "Vorläufige Übersetzung. Bitte Southwest fragen, wenn etwas unklar ist.",
  "Arbeitssicherheit und Einweisung",
  "Testportal v21.4 · Kein Zugang zur Mitarbeiterübersicht",
  "Registrierung für Arbeiter",
  "Vollständiger Name",
  "Unternehmen",
  "Gewerk",
  "Tätigkeit",
  "Ich verstehe, dass das Sicherheitsteam von Southwest diese Angaben überprüft.",
  "Mein Arbeiterprofil erstellen",
  "Bereits registriert? Fordern Sie bei Southwest einen sicheren Rückkehr-Link an. Durch erneute Registrierung wird kein bestehendes Profil geöffnet.",
  "Beenden",
  "Was möchten Sie tun?",
  "Sie können mit beiden Aufgaben beginnen.",
  "Ihr aktueller Status",
  "Einweisung",
  "Eingereichte Zertifikate",
  "Von Southwest bestätigt",
  "Eingereicht · wartet auf Sicherheitsleitung",
  "Nicht abgeschlossen",
  "Kein Ablaufdatum angegeben",
  "Wartet auf Prüfung durch Southwest",
  "Bestätigt",
  "In Prüfung",
  "Machen Sie ein deutliches Foto oder laden Sie eine PDF hoch. Southwest liest die Angaben aus und prüft sie. Keine Eingabe nötig.",
  "Wird gelesen und übermittelt…",
  "Abschnitt",
  "von",
  "Erklärung und Unterschrift",
  "Ich bestätige, dass ich die Sicherheitsunterweisung von Southwest abgeschlossen habe, meine Pflichten verstehe und die Sicherheitsregeln sowie die geltenden Anforderungen von Nova Scotia einhalte.",
  "Ich stimme dieser Erklärung zu.",
  "Vollständigen Namen als Unterschrift eingeben",
  "Der Abschluss wartet auf die Bestätigung der Sicherheitsleitung.",
  "Einweisung zur Prüfung senden",
  "Übersetzung nicht verfügbar. Fahren Sie nicht in einer Sprache fort, die Sie nicht verstehen. Bitten Sie Southwest um Hilfe.",
  "Audio ist auf diesem Gerät nicht verfügbar",
  "Foto oder PDF auswählen",
  "Bitte eine Datei unter 2 MB auswählen",
  "Zertifikat zur Prüfung an Southwest gesendet.",
  "Sicherheitsinformationen werden übersetzt…",
  "Fragen Sie Southwest, wenn etwas unklar ist."
 ]
};
const I18N_KEYS=["language", "intro", "orientationButton", "certButton", "photoButton", "sendCert", "listen", "ackSection", "knowledge", "continue", "back", "correct", "retry", "draft", "appTitle", "testPortal", "registerTitle", "name", "company", "trade", "occupation", "consent", "createProfile", "returning", "exit", "chooseAction", "eitherFirst", "statusTitle", "orientation", "certCount", "verified", "pending", "incomplete", "noExpiry", "pendingTicket", "verifiedTicket", "ticketPending", "uploadInfo", "reading", "section", "of", "declarationTitle", "declarationBody", "declarationCheck", "signName", "awaitingReview", "submitOrientation", "translationError", "audioUnavailable", "chooseFile", "fileTooBig", "uploadComplete", "loadingTranslation", "helpTranslation"];

async function api(action,fields){const r=await fetch('/api/worker-portal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...fields})});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
function Labeled({label,children}){return <label style={{display:'grid',gap:6,fontSize:13,color:muted}}>{label}{children}</label>}
export default function WorkerPortal(){
 const [language,setLanguage]=useState(()=>sessionStorage.getItem('safety-lang')||'en'),[localized,setLocalized]=useState({}),[translating,setTranslating]=useState(false),[token,setToken]=useState(()=>new URLSearchParams(window.location.search).get('session')||sessionStorage.getItem(sid())||''),[worker,setWorker]=useState(null),[form,setForm]=useState({name:'',company:'',trade:'',occupation:''}),[consent,setConsent]=useState(false),[screen,setScreen]=useState('home'),[error,setError]=useState(''),[working,setWorking]=useState(false),[cert,setCert]=useState({type:'',issued_date:'',expiry_date:'',notes:''}),[file,setFile]=useState(null),[step,setStep]=useState(0),[questions,setQuestions]=useState(()=>selectQuestions(0)),[ack,setAck]=useState(false),[sections,setSections]=useState([]),[signature,setSignature]=useState(''),[declaration,setDeclaration]=useState(false);
 useEffect(()=>{sessionStorage.setItem('safety-lang',language);window.speechSynthesis?.cancel?.()},[language]);
 const T=(id)=>{const i=typeof id==='number'?id:I18N_KEYS.indexOf(id);return (I18N[language]||I18N.en)[i]||I18N.en[i]||id};
 const spoken=(text)=>{if(!('speechSynthesis' in window))return setError(T('audioUnavailable'));window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=({en:'en-CA',fr:'fr-CA',es:'es-ES',ar:'ar',uk:'uk-UA',de:'de-DE'})[language];u.rate=.9;window.speechSynthesis.speak(u)};
 const entered=useRef(Date.now()),visible=useRef(0),hidden=useRef(false),started=useRef(new Date().toISOString());
 const act=async(action,data={},callback)=>{setWorking(true);setError('');try{const res=await api(action,data);callback?.(res);return res;}catch(e){setError(e.message);return null;}finally{setWorking(false)}};
 useEffect(()=>{if(token){sessionStorage.setItem(sid(),token);act('profile',{token},r=>setWorker(r.worker));}},[]);
 useEffect(()=>{const fn=()=>{if(document.hidden&&!hidden.current){visible.current+=Date.now()-entered.current;hidden.current=true}else if(!document.hidden&&hidden.current){entered.current=Date.now();hidden.current=false}};document.addEventListener('visibilitychange',fn);return()=>document.removeEventListener('visibilitychange',fn)},[]);
 const time=()=>Math.round((visible.current+(!hidden.current?Date.now()-entered.current:0))/1000);
 function logout(){sessionStorage.removeItem(sid());setToken('');setWorker(null);setScreen('home')}
 async function register(){const r=await act('register',{...form,consent,language},r=>{sessionStorage.setItem(sid(),r.token);setToken(r.token);setWorker(r.worker)});if(r)setScreen('home')}
 async function addCert(){if(!file)return setError(T('chooseFile'));if(file.size>2100000)return setError(T('fileTooBig'));setWorking(true);setError('');try{const data=await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(file)});const r=await api('ticket_auto',{token,attachment:{name:file.name,type:file.type,data}});setWorker(r.worker);setCert({type:'',issued_date:'',expiry_date:'',notes:''});setFile(null);setScreen('home')}catch(e){setError(e.message)}finally{setWorking(false)}}
 function proceed(){if(!ack||questions.some(q=>!q.answered))return;const section={title:SECTIONS[step].title,language,displayed_translation:language!=='en'?{title:loc?.title||null,points:loc?.points||null,questions:loc?.questions||null}:null,elapsed_seconds:time(),acknowledged_at:new Date().toISOString(),questions:questions.map(q=>({prompt:q.prompt,attempts:q.attempts,correct:true}))};setSections(s=>[...s,section]);visible.current=0;entered.current=Date.now();hidden.current=document.hidden;setAck(false);if(step===SECTIONS.length-1)setScreen('sign');else{setStep(step+1);setQuestions(selectQuestions(step+1))}}
 async function complete(){const r=await act('orientation',{token,sections,language,signature,acknowledged:declaration,started_at:started.current},r=>setWorker(r.worker));if(r){setScreen('home');setSections([]);setStep(0);setQuestions(selectQuestions(0));setSignature('');setDeclaration(false)}}
 const start=()=>{setStep(0);setSections([]);setQuestions(selectQuestions(0));setAck(false);started.current=new Date().toISOString();visible.current=0;entered.current=Date.now();hidden.current=document.hidden;setScreen('lesson')};
 useEffect(()=>{if(!worker||screen!=='lesson'||language==='en')return;let cancelled=false;const q=questions.map(v=>({prompt:v.prompt,options:v.options.map(o=>o.label)}));const key=language+'-'+step+'-'+q.map(v=>v.prompt).join('|');if(localized[key])return;setTranslating(true);api('translate',{token,language,section_index:step,title:SECTIONS[step].title,points:SECTIONS[step].points,questions:q}).then(r=>{if(!cancelled)setLocalized(x=>({...x,[key]:r.translation}))}).catch(()=>{if(!cancelled)setError(T('translationError'))}).finally(()=>{if(!cancelled)setTranslating(false)});return()=>{cancelled=true}},[worker,screen,step,language,questions.map(q=>q.prompt).join('|')]);
 const translationKey=language+'-'+step+'-'+questions.map(q=>q.prompt).join('|');const loc=localized[translationKey];const translationReady=language==='en'||(loc&&Array.isArray(loc.points)&&loc.questions?.length===questions.length);const rtl=language==='ar';
 const item=(children)=> <div style={{background:panel,border:'1px solid #263448',padding:18,borderRadius:14,marginBottom:15}}>{children}</div>;
 return <main dir={rtl?'rtl':'ltr'} lang={language} style={{minHeight:'100vh',background:bg,color:light,fontFamily:'Segoe UI,Arial,sans-serif',padding:'22px 14px 60px'}}><div style={{maxWidth:560,margin:'auto',textAlign:rtl?'right':'left'}}><header style={{marginBottom:22}}><div style={{color:teal,fontWeight:800,letterSpacing:1,fontSize:13}}>SOUTHWEST · FORTUNA</div><label style={{display:'grid',gap:6,marginTop:15,color:muted,fontSize:13}}>{T(0)}<select aria-label='Orientation language' style={input} value={language} onChange={e=>setLanguage(e.target.value)}>{LANGUAGES.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><h1 style={{fontSize:25,margin:'9px 0'}}>{T('appTitle')}</h1><div style={{color:muted,fontSize:13}}>{T('testPortal')}</div></header>{error&&<div role="alert" style={{padding:12,background:'#541d27',borderRadius:9,color:'#fecaca',marginBottom:16}}>{language==='en'?error:T('helpTranslation')}</div>}
 {!worker?item(<><h2>{T('registerTitle')}</h2><p style={{color:muted}}>{T(1)}</p><div style={{display:'grid',gap:14}}>{[[T('name'),'name'],[T('company'),'company'],[T('trade'),'trade'],[T('occupation'),'occupation']].map(([label,k])=><Labeled key={k} label={label}><input style={input} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></Labeled>)}<label style={{display:'flex',gap:9,fontSize:13}}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> {T('consent')}</label><button style={button} disabled={working||!consent||!form.name||!form.company||!form.trade} onClick={register}>{T('createProfile')}</button><p style={{color:muted,fontSize:12}}>{T('returning')}</p></div></>):<>
 <div style={{display:'flex',justifyContent:'space-between',gap:9,alignItems:'center',marginBottom:12}}><div><strong>{worker.name}</strong><div style={{color:muted,fontSize:12}}>{worker.trade} · {worker.company}</div></div><button style={{...button,background:'#253348',color:light,padding:9}} onClick={logout}>{T('exit')}</button></div>
 {screen==='home'&&<>{item(<><h2 style={{marginTop:0}}>{T('chooseAction')}</h2><p style={{color:muted}}>{T('eitherFirst')}</p><div style={{display:'grid',gap:12}}><button style={button} onClick={start}>{T(2)} →</button><button style={{...button,background:'#27394b',color:light}} onClick={()=>setScreen('upload')}>{T(3)} →</button></div></>)}{item(<><h3>{T('statusTitle')}</h3><p>{T('orientation')}: <strong>{worker.orientation?.approval_status==='approved'?T('verified'):worker.orientation?.status==='completed'?T('pending'):T('incomplete')}</strong></p><p>{T('certCount')}: <b>{worker.tickets?.length||0}</b></p>{(worker.tickets||[]).map(t=><p key={t.id} style={{color:muted,fontSize:13}}>{t.type} · {t.expiry_date||T('noExpiry')} · {t.status==='verified'?T('verifiedTicket'):T('ticketPending')}</p>)}<p style={{color:muted,fontSize:12}}>{T('pendingTicket')}</p></>)}</>}
 {screen==='upload'&&item(<><h2>{T(3)}</h2><p style={{color:muted}}>{T('uploadInfo')}</p><div style={{display:'grid',gap:14}}><Labeled label={T(4)}><input style={input} type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></Labeled>{file&&<p style={{color:teal,fontSize:13}}>{file.name}</p>}<button style={button} disabled={working||!file} onClick={addCert}>{working?T('reading'):T(5)}</button><button style={{...button,background:'#253348',color:light}} onClick={()=>setScreen('home')}>{T(10)}</button></div></>)}
 {screen==='lesson'&&item(<><div style={{color:teal,fontWeight:800}}>{T('section')} {step+1} {T('of')} {SECTIONS.length}</div><h2>{translationReady?(loc?.title||SECTIONS[step].title):T('loadingTranslation')}</h2><button style={{...button,background:'#263548',color:light}} disabled={!translationReady} onClick={()=>spoken([loc?.title||SECTIONS[step].title,...(loc?.points||SECTIONS[step].points)].join('. '))}>{T(6)} ▶</button>{(translationReady?(loc?.points||SECTIONS[step].points):[]).map((p,i)=><p key={i} style={{background:bg,padding:12,borderRadius:8,lineHeight:1.6}}>{p}</p>)}<label style={{display:'flex',gap:10,margin:'16px 0'}}><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> {T(7)}</label><h3>{T(8)}</h3>{translationReady&&questions.map((q,i)=><div key={q.prompt} style={{borderTop:'1px solid #334155',padding:'14px 0'}}><strong>{i+1}. {loc?.questions?.[i]?.prompt||q.prompt}</strong><button style={{...button,marginInlineStart:8,padding:5,background:'#263548',color:light}} onClick={()=>spoken(loc?.questions?.[i]?.prompt||q.prompt)}>▶ {T(6)}</button>{q.options.map((choice,j)=><button key={j} disabled={q.answered} onClick={()=>setQuestions(arr=>arr.map((x,n)=>n===i?{...x,attempts:x.attempts+1,answered:choice.correct}:x))} style={{...button,width:'100%',textAlign:rtl?'right':'left',marginTop:9,background:q.answered&&choice.correct?'#18392f':'#263548',color:light}}>{loc?.questions?.[i]?.options?.[j]||choice.label}</button>)}<p style={{fontSize:13,color:q.answered?'#22C55E':muted}}>{q.answered?T(11):q.attempts?T(12):T(8)}</p></div>)}{!translationReady&&<p role='status' style={{color:'#EAB308'}}>{T('translationError')}</p>}{language!=='en'&&<p style={{color:'#EAB308',fontSize:12}}>{T(13)}</p>}<button style={{...button,width:'100%'}} disabled={!translationReady||translating||!ack||questions.some(q=>!q.answered)} onClick={proceed}>{T(9)} →</button></>)}
 {screen==='sign'&&item(<><h2>{T('declarationTitle')}</h2><p style={{lineHeight:1.7}}>{T('declarationBody')}</p><label style={{display:'flex',gap:9,marginBottom:15}}><input type="checkbox" checked={declaration} onChange={e=>setDeclaration(e.target.checked)}/> {T('declarationCheck')}</label><Labeled label={T('signName')}><input style={input} value={signature} onChange={e=>setSignature(e.target.value)}/></Labeled><p style={{color:muted,fontSize:13}}>{T('awaitingReview')}</p><button style={{...button,width:'100%'}} disabled={working||!declaration||!signature.trim()} onClick={complete}>{T('submitOrientation')}</button></>)}
 </>}</div></main>;
}
